### ISSUE TITLE
Error while generating PDF

### ISSUE THREAD

**Issue by lask79** [asciidoctor/asciidoctorj#377]
After updating from 1.5.0-alpha.8 to 1.5.0-alpha.9 I am getting the following error:

Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc (generate-pdf) on project #####: Execution generate-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc failed: (NoMethodError) undefined method `margins' for nil:NilClass

Can anyone help me out?

Regards
Lasse

**Comment by mojavelinux** [comment]
We'll either need a more complete stacktrace or a link to the document because there's no enough information here to know what to look for. Could you provide one of the two? The document (or one that causes the same error) would be ideal.

**Comment by dsdolzhenko** [comment]
I have the same problem with version 1.5.0-alpha.9.

Here is a document that I tried to convert
```Asciidoc
Дмитрий Долженко
================

```

And here is a stack-trace that I got
```
/usr/local/lib/ruby/gems/2.2.0/gems/prawn-2.0.2/lib/prawn/document.rb:668:in `generate_margin_box': undefined method `margins' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/prawn-2.0.2/lib/prawn/document.rb:307:in `go_to_page'
	from /usr/local/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:1883:in `layout_running_content'
	from /usr/local/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:176:in `convert_document'
	from /usr/local/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-1.5.0.alpha.9/lib/asciidoctor-pdf/converter.rb:97:in `convert'
	from /usr/local/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1028:in `convert'
	from /usr/local/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1499:in `convert'
	from /usr/local/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/asciidoctor-pdf-1.5.0.alpha.9/bin/asciidoctor-pdf:27:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:23:in `load'
	from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
```

**Comment by mojavelinux** [comment]
This happens if the document has no content, only a title page (and other front matter pages). If you add a least one block of content, you won't see this error...and it also means I know how to fix it.

**Comment by mojavelinux** [comment]
Btw, this is an Asciidoctor PDF issue, not an AsciidoctorJ PDF issue.

**Comment by mojavelinux** [comment]
Resolved by https://github.com/asciidoctor/asciidoctor-pdf/commit/b6a0df9e06a9b5640e6c68634cb8a745f46e558d

**Comment by mojavelinux** [comment]
This will be available in the next release. As a workaround, just add content to your document.

**Comment by GrahamGIGA** [comment]
I was getting no icons in my pdf, so followed the advice in an earlier bug report and added -a icons-font to the cl call:

**Comment by mojavelinux** [comment]
@GrahamGIGA Can you enable the `--trace` flag so that we can see what the cause of the error is?

(You are correct that the order of flags doesn't matter).

**Comment by GrahamGIGA** [comment]
Here ya go!

Grahams-MacBook-Pro-2:setup graham$ asciidoctor-pdf -b book --trace  Setup.adoc
asciidoctor: ERROR: Setup.adoc: line 3: only book doctypes can contain level 0 sections
/usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/inline.rb:38:in `convert': asciidoctor: FAILED: /Users/graham/Git/Documentation/setup/Setup.adoc: Failed to load AsciiDoc document - undefined method `convert' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:1183:in `convert_quoted_text'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:391:in `block (2 levels) in sub_quotes'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:391:in `gsub!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:391:in `block in sub_quotes'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:390:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:390:in `sub_quotes'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:113:in `block in apply_subs'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:108:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:108:in `apply_subs'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/substitutors.rb:150:in `apply_title_subs'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/abstract_block.rb:128:in `title'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/section.rb:89:in `generate_id'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/parser.rb:1607:in `initialize_section'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/parser.rb:260:in `next_section'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/parser.rb:303:in `next_section'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/parser.rb:303:in `next_section'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/parser.rb:67:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:472:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1347:in `load'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1465:in `convert'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:95:in `block in invoke!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `invoke!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.15/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:22:in `load'
	from /usr/local/bin/asciidoctor-pdf:22:in `<main>'
Grahams-MacBook-Pro-2:setup graham$

**Comment by mojavelinux** [comment]
Thanks. The problem is that the converter is not being properly
initialized, hence the NilClass. I don't yet know why.

**Comment by mojavelinux** [comment]
Aha. I've seen this before as I've made the same mistake. -b is for setting
the backend. You are passing the value book, which is not a valid backend
name. Hence the converter never gets initialized. What you probably meant
to type is -d book. When using asciidoctor-pdf you don't have to specify
the backend.

Asciidoctor needs to fail (or warn) more gracefully in this circumstance.
I'll figure out where the logic needs to go to make that happen.

**Comment by GrahamGIGA** [comment]
Ah, the famous upside-down user error.  

Bummer, thanks!

**Comment by mojavelinux** [comment]
I'm glad you pointed this out, though, because the application should guide the user back to safety.

**Comment by GrahamGIGA** [comment]
I agree, elegant degradation is the order of the day.

Cheers

Graham
