### ISSUE TITLE
Chain commands in JavaExtensionRegistry

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#487]
It would be useful if the methods in the JavaExtensionRegistry supported method chaining. This would allow extensions to be registered in a single call and avoid having to assign the registry to a local variable.

``` java
asciidoctor.javaExtensionRegistry()
    .block(TabContainerBlock.class);
    .block(TabBlock.class);
```

The RubyExtensionRegistry already has this feature, which even further justifies why we should do it.

**Comment by robertpanzer** [comment]
Makes complete sense. 
If I'm not wrong this will break binary compatibility though, which should in particular break the maven plugin.
(Just a reminder that we keep track of it)

**Comment by mojavelinux** [comment]
That's why I proposed it for 1.6.0 only. Since we are still in alpha, breaking binary compatibility is still on the table.

In fact, at this point, I think all new features and API changes should only go to 1.6.0. We can continue to work on 1.5.x to fix existing functionality.

**Comment by robertpanzer** [comment]
Yes, definitely!

I was just mentioning this as we already spent some effort in making the maven plugin compatible with 1.6.

**Comment by mojavelinux** [comment]
:+1:

**Comment by robertpanzer** [comment]
Just for documentation purposes, this is what you will see after that change without an updated maven plugin:
```
Caused by: java.lang.NoSuchMethodError: org.asciidoctor.extension.JavaExtensionRegistry.treeprocessor(Ljava/lang/Class;)V
	at org.asciidoctor.maven.extensions.AsciidoctorJExtensionRegistry.register(AsciidoctorJExtensionRegistry.java:56)
	at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:182)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 26 more
```

**Comment by mojavelinux** [comment]
Is that just because the signature of the method changed (the return type)?

**Comment by robertpanzer** [comment]
Yes exactly.

This will require the asciidoctor-maven-plugin to invoke the method using reflection.

Will provide PRs for both at the same time once I have them finished.

**Comment by abelsromero** [comment]
First, no issue with impacting the maven-plugin, test should capture this and I am more than happy to fix it.
Then, following @mojavelinux comment, I don't see why it should break the current implementation, if the only change is the return type, in fact the error message seems to fail in JavaExtensionRegistry, not the maven plugin itself.

**Comment by abelsromero** [comment]
@robertpanzer I check you'r repo and could not see the branch with the changes. Is there any I can look?

**Comment by robertpanzer** [comment]
I didn’t do any changes yet.

The thing is, that if you change the return type of a method, a caller that is not recompiled will not find that method any more.
That’s why the asciidoctor-maven-plugin will get a NoSuchMethodError once I change the return type of the methods in JavaExtensionRegistry from void to JavaExtensionRegistry.

Does that make sense?

Cheers,
Robert

**Comment by abelsromero** [comment]
> Does that make sense?

Yes, makes sense :+1: and now I understand the stacktrace, the issue is the `V` at the end of the signature. But still that would affect someone using a 1.5.x version of the plugin with Asciidoctorj 1.6.x which in my opinion is not a compatible scenario. I think this will be a communication challenge and will require clear documentation.

**Comment by robertpanzer** [comment]
Yes, exactly!

While it is irrelevant when using Reflection it is used for resolving compiled method calls.

Thing is we're already pushing users that have problems with extensions to 1.6.0 Alpha versions or even Snapshots.
And we already modified the maven plugin once to play nice with 1.6.0 in https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/218

I am also a bit unsure about the right way to go:
1. Should we try to support both versions or 
2. should we, just like AsciidoctorJ, create another branch of the asciidoctor-maven-plugin that is 1.6.0 only and let the user build the plugin himself?

**Comment by abelsromero** [comment]
I am split also.
I heart tells me to go for option 1, for the sake of offering more flexibility to users and the technical challenge, which is small, but integration reflection is still something to keep in mind.

But on the other side, my mind tells me avoid reflection for the sake of maintenance and keeping things simple. After all, it’s a maven plugin, what I mean is that this is not the type of component that someone may need to lock. Only reason not to upgrade is because they use Java 6, and that will prevent also AsciidoctorJ.

Still, if you aske me, option 1 :smile:

**Comment by mojavelinux** [comment]
@Mogztter Do you have any thoughts about this API? It would be good to make a decision either way before the 1.6.0 release. I was just trying to make this a little more fluent for extension writers, but if this ends up being more trouble than it's worth, then we should probably abandon the idea.

**Comment by Mogztter** [comment]
@mojavelinux It's not already the case ? Every methods in `JavaExtensionRegistry` returns a `JavaExtensionRegistry` and the implementation returns `this`:

https://github.com/asciidoctor/asciidoctorj/blob/3ce454b9c26f4c350fc515707fd51ffa7488ea87/asciidoctorj-core/src/main/java/org/asciidoctor/internal/JavaExtensionRegistryImpl.java#L175-L179

I need to write a test to make sure that it's working but it looks like we can already do:

```java
asciidoctor.javaExtensionRegistry()
    .block(TabContainerBlock.class);
    .block(TabBlock.class);
```

**Comment by mojavelinux** [comment]
That's great news! Yeah, let's get a test in there, then wrap this issue up. :candy:
