### ISSUE TITLE
Cant load AsciidoctorJ on Jenkins plugins 

### ISSUE THREAD

**Issue by rmpestano** [asciidoctor/asciidoctorj#442]
Hi guys, 

I'm trying to use AsciidoctorJ on a jenkins plugin but the following error is raised when Asciidoctor.Factory.create(); is called:

```
ERROR: Publisher com.github.cukedoctor.jenkins.CukedoctorPublisher aborted due to exception
java.lang.NoSuchMethodError: jnr.constants.platform.OpenFlags.defined()Z
at org.jruby.RubyFile.createFileClass(RubyFile.java:149)
at org.jruby.Ruby.initCore(Ruby.java:1545)
at org.jruby.Ruby.bootstrap(Ruby.java:1330)
```

Here is the plugin maven dependencies:

```
 <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>1.5.0-alpha.11</version>
        </dependency>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>1.5.4</version>
        </dependency>
        <dependency>
            <groupId>org.jruby</groupId>
            <artifactId>jruby-complete</artifactId>
            <version>9.0.5.0</version>
        </dependency>
```

more details here: https://github.com/rmpestano/cukedoctor-jenkins-plugin/issues/1

thanks in advance.

**Comment by mojavelinux** [comment]
Is this happening on a specific operating system, or on all operating systems?

**Comment by rmpestano** [comment]
Hi Dan, its on lunux (Ubuntu 15)  but I will test on windows as soon I get in the work.

**Comment by robertpanzer** [comment]
I would guess that there is some old version of JRuby available from somewhere.
The method `jnr.constants.platform.OpenFlags.defined()` was defined sometime around mid 2014 and for example JRuby 1.7.12 contains the class, but not this method.
If it works in your CLI and not in Jenkins, I would suspect that Jenkins uses an old version of JRuby.
Maybe @lordofthejars could chime in, he surely has some more knowledge about Jenkins :-)

**Comment by mojavelinux** [comment]
@rmpestano I was only asking about Windows because that's what the JRuby issue you reference in the upstream issue points to (https://github.com/jruby/jruby/issues/3332). So perhaps that isn't the underlying problem at hand.

**Comment by mojavelinux** [comment]
I think it's more likely what @robertpanzer is saying.

**Comment by rmpestano** [comment]
Looks like I need 'jenkins-plugin-runtime' gem installed: https://github.com/jenkinsci/jenkins.rb/wiki/Getting-Started-With-Ruby-Plugins

can't test it here at the company (can't even install a downloaded gem ;( )

thank you so far.

**Comment by rmpestano** [comment]
I've got exactly same stacktrace on windows, I'll try with jenkins-runtime gem when I got home.

**Comment by rmpestano** [comment]
Interesting fact, I have a maven plugin which [executes the same steps](https://github.com/rmpestano/cukedoctor/blob/master/cukedoctor-maven-plugin/src/main/java/com/github/cukedoctor/mojo/CukedoctorMojo.java#L144) that [jenkins plugin executes](https://github.com/rmpestano/cukedoctor-jenkins-plugin/blob/master/src/main/java/com/github/cukedoctor/jenkins/CukedoctorPublisher.java#L168)  but the maven plugin can load asciidoctor and convert files even when maven plugin is executed in a jenkins job.

Looks like its more a missing configuration in jenkins plugin than an environment issue.

Any hints?

**Comment by rmpestano** [comment]
Hi again, some progress here.

When I downgrade jruby to 1.7.x. I don't get 'NoSuchMethodError: jnr.constants.platform.OpenFlags.defined()' instead I receive:

```
org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- jruby/java
```

but then if I set Asciidoctor classloader here:

```
Asciidoctor.Factory.create(CukedoctorPublisher.class.getClassLoader());
```

then html documentation is generated successfuly! 

the only problem now is **pdf** which somewhat depends on jruby 9.x, right?

here is the stacktrace for pdf backend:


```
org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (EBADF) Bad file descriptor - asciidoctor: FAILED: C:/projetos/cukedoctor-jenkins-plugin/work/jobs/teste/workspace/living-documentation/documentation.adoc: Failed to load AsciiDoc document - Bad file descriptor - Bad file descriptor
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:345)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:549)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.execute(CukedoctorPublisher.java:167)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.perform(CukedoctorPublisher.java:146)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: org.jruby.exceptions.RaiseException: (EBADF) Bad file descriptor - asciidoctor: FAILED: C:/projetos/cukedoctor-jenkins-plugin/work/jobs/teste/workspace/living-documentation/documentation.adoc: Failed to load AsciiDoc document - Bad file descriptor - Bad file descriptor
	at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1411)
	at org.jruby.RubyKernel.warn(org/jruby/RubyKernel.java:1351)
	at RUBY.next_block(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:484)
	at Asciidoctor::Parser.parse_blocks(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:1132)
	at Asciidoctor::Parser.build_block(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:1115)
	at RUBY.next_block(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:855)
	at Asciidoctor::Parser.parse_blocks(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:1132)
	at Asciidoctor::Parser.build_block(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:1115)
	at RUBY.next_block(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:855)
	at Asciidoctor::Parser.next_section(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:315)
	at Asciidoctor::Parser.next_section(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:303)
	at RUBY.next_section(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:303)
	at RUBY.next_section(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:303)
	at RUBY.parse(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:67)
	at RUBY.parse(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:471)
	at RUBY.load(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1344)
	at RUBY.convert(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1462)
	at RUBY.convert_file(C:/Users/rafael-pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl666964712.convertFile(org/jruby/gen/InterfaceImpl666964712.gen:13)
```

With jruby-complete 9.x I always got:

```
java.lang.NoSuchMethodError: jnr.constants.platform.OpenFlags.defined()Z
	at org.jruby.RubyFile.createFileClass(RubyFile.java:149)
```

**Comment by robertpanzer** [comment]
Hi Rafael,

AsciidoctorJ 1.5.x is still delivered with JRuby 1.7.21. 1.7.24 should also work.
When running on Windows there are currently some issues with JRuby 9K, so I recommend not using it on Win.
It could be that the maven plugin uses 1.7.23, which stumbles over this with asciidoctorj-pdf: https://github.com/jruby/jruby/issues/3496

Please try to set the version of jruby-complete to 1.7.24.

Cheers
Robert

**Comment by rmpestano** [comment]
Hi @robertpanzer, just came here to confirm that!

working great also for pdf, the stacktrace I posted above was caused by a misconfiguration in adoc file.

To summarize: working with jruby 1.7.24 setting Asciidoctor classloader to plugin classloader.

Thank you so much for the help!

**Comment by rmpestano** [comment]
Hi guys, 

It's quite "embarrassing" but I can't make it work on linux ;(. 

I made it work on windows (at my company) and a clean windows machine (which I didn't used for years) I have at home.

Here is the stacktrace:

```

ERROR: Build step failed with exception
org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NotImplementedError) stat unsupported or native support failed to load
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:345)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:549)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.execute(CukedoctorPublisher.java:185)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.perform(CukedoctorPublisher.java:155)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: org.jruby.exceptions.RaiseException: (NotImplementedError) stat unsupported or native support failed to load
	at org.jruby.RubyFile.mtime(org/jruby/RubyFile.java:457)
	at RUBY.load(/home/pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1311)
	at RUBY.convert(/home/pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1462)
	at RUBY.convert_file(/home/pestano/.m2/repository/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl1760938920.convertFile(org/jruby/gen/InterfaceImpl1760938920.gen:13)
```

Will reopen the issue while we don't find a solution.

**Comment by mojavelinux** [comment]
This sounds like the root of the solution.

https://github.com/jruby/jruby/issues/1754

In short, it's some sort of library conflict that impacts JRuby.

**Comment by rmpestano** [comment]
I also opened an issue at jenkins Jira: https://issues.jenkins-ci.org/browse/INFRA-616.

**Comment by rmpestano** [comment]
As per jira issue looks like we will have to solve the issue on asciidoctor side.

I've tested on another (clean) linux distro (rhel 7) and the issue is the same but looking at the stacktrace now the issue is not on **loading** asciidoctor anymore but in document conversion itself.

**Comment by rmpestano** [comment]
Just found it works with asciidoctorJ 1.5.1 (jruby 1.7.9). Don't know on windows now hehe

**Comment by rmpestano** [comment]
The "upper bound" dependency for Jruby is 1.7.13, this way I could make the AsciidoctorJ (1.5.4) work on linux (both for html and pdf backend).

Note that the classloading 'trick' mentioned in [this comment](https://github.com/asciidoctor/asciidoctorj/issues/442#issuecomment-199777731) is still needed in any case (win or linux) otherwise the plugin will throw:

```
org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- jruby/java
```

there is any problem using AsciidoctorJ with an old version of jruby?

sorry for the spams  :pensive:

Lets see how things goes on windows now :pray:

**Comment by rmpestano** [comment]
working on windows also ;), will close the issue. Thanks for the help.

**Comment by robertpanzer** [comment]
Could it be that a GEM_PATH is leaking through?
Can you try passing (String) null to the create() method?

Am Mittwoch, 23. März 2016 schrieb Rafael M. Pestano :

**Comment by rmpestano** [comment]
Hi Robert,
You mean this:

```
   asciidoctor = Asciidoctor.Factory.create("null");
```

It throws the same exception: 'no such file to load -- jruby/java'

**Comment by mojavelinux** [comment]
Nope, it should be:

```
asciidoctor = Asciidoctor.Factory.create((String) null);
```

**Comment by rmpestano** [comment]
same error, it look like the plugin is loaded by a different classloader then its dependencies...

**Comment by render1980** [comment]
I had the same problem with `asciidoctorj-pdf` plugin:

```
Caused by: java.lang.NoSuchMethodError: jnr.constants.platform.OpenFlags.defined()Z
        at org.jruby.RubyFile.createFileClass(RubyFile.java:151)
        at org.jruby.Ruby.initCore(Ruby.java:1490)
        at org.jruby.Ruby.bootstrap(Ruby.java:1274)
        at org.jruby.Ruby.init(Ruby.java:1173)
        at org.jruby.Ruby.newInstance(Ruby.java:338)
        at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:79)
        at org.asciidoctor.internal.JRubyAsciidoctor.createJRubyAsciidoctorInstance(JRubyAsciidoctor.java:119)
        at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:62)
        at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:683)
        at org.asciidoctor.gradle.AsciidoctorTask.instantiateAsciidoctor(AsciidoctorTask.groovy:630)
        at org.asciidoctor.gradle.AsciidoctorTask.processAsciidocSources(AsciidoctorTask.groovy:577)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
```

but it was fixed after adding `settings.gradle` to gradle project in child directory.

Nevertheless, the problem reproduces again when I run `gradle build` from parent gradle project. `Build` phase is depend on `asciidoctor` phase at child gradle project. When I run `gradle build` in child project, it end successfully. I don't know yet how to fix it.

**Comment by rmpestano** [comment]
Hi @render1980,

this issue is related to a Jenkins plugin ([this one](https://github.com/jenkinsci/cucumber-living-documentation-plugin)) which uses AsciidoctorJ on the jenkins plugin itself.  

Your problem seems to be related to a gradle build and that should be ok. As you can see on [this comment](https://github.com/asciidoctor/asciidoctorj/issues/442#issuecomment-199567935) there is no issue when asciidoctorJ is used via maven plugin during application build.

**Comment by render1980** [comment]
Hi @rmpestano

Thanks for advice. But the reason is not quite that.

The reason as I've understood that parent project doesn't see `jnr-constants` in classpath (on static linking stage). I've added this dependency to classpath and it works (last string in `dependencies` section):

```
dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath('se.transmode.gradle:gradle-docker:1.2')
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:latest.release"

        classpath 'com.github.jnr:jnr-constants:0.9.9'
    }
```

**Comment by rmpestano** [comment]
Hi @render1980, thank you for the info.

I still get the exception:

```Exception in thread "pool-13-thread-1" java.lang.NoSuchMethodError: jnr.constants.platform.OpenFlags.defined()Z
        at org.jruby.RubyFile.createFileClass(RubyFile.java:149)
        at org.jruby.Ruby.initCore(Ruby.java:1491)
        at org.jruby.Ruby.bootstrap(Ruby.java:1275)
        at org.jruby.Ruby.init(Ruby.java:1174)
        at org.jruby.Ruby.newInstance(Ruby.java:339)
        at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:79)
        at org.asciidoctor.internal.JRubyAsciidoctor.createJRubyAsciidoctorInstance(JRubyAsciidoctor.java:129)
        at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:72)
        at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:695)
```
 Here is the plugin classpath:
![classpath](https://user-images.githubusercontent.com/1592273/30484397-a21f70d6-9a00-11e7-961e-e27235bfdb73.png)

**Comment by rmpestano** [comment]
Note that I can even load the OpenFlags before classing Asciidoctor.create
 ```
Class.forName("jnr.constants.platform.OpenFlags")
```
but still got same exception.

I've also printed OpenFlags methods:

```
Method: description - return: class java.lang.String
Parameters: 
Method: toString - return: class java.lang.String
Parameters: 
Method: values - return: class [Ljnr.constants.platform.OpenFlags;
Parameters: 
Method: intValue - return: int
Parameters: 
Method: longValue - return: long
Parameters: 
Method: valueOf - return: class jnr.constants.platform.OpenFlags
Parameters: 
arg0,Method: valueOf - return: class jnr.constants.platform.OpenFlags
Parameters: 
arg0,Method: name - return: class java.lang.String
Parameters: 
Method: equals - return: boolean
Parameters: 
arg0,Method: hashCode - return: int
Parameters: 
Method: compareTo - return: int
Parameters: 
arg0,Method: compareTo - return: int
Parameters: 
arg0,Method: valueOf - return: class java.lang.Enum
Parameters: 
arg0,arg1,Method: getDeclaringClass - return: class java.lang.Class
Parameters: 
Method: ordinal - return: int
Parameters: 
Method: wait - return: void
Parameters: 
arg0,arg1,Method: wait - return: void
Parameters: 
arg0,Method: wait - return: void
Parameters: 
Method: getClass - return: class java.lang.Class
Parameters: 
Method: notify - return: void
Parameters: 
Method: notifyAll - return: void
Parameters: 
```

**Comment by rmpestano** [comment]
Alright, got it working now!

Jenkins plugins first look into jenkins libs by default but we can change that in the hpi-plugin:

```
 <plugin>
                <groupId>org.jenkins-ci.tools</groupId>
                <artifactId>maven-hpi-plugin</artifactId>
                <configuration>
                    <pluginFirstClassLoader>true</pluginFirstClassLoader>
                </configuration>
            </plugin>
``` 
Note that in this case there is no need to add 'com.github.jnr:jnr-constants:0.9.9' dependency because it is already bundled in jruby-complete.

Thank you very much for all the help!
